--
-- PostgreSQL database dump
--

\restrict A7ATLIsPnIEfaY9r3cfj13H6G1ykKsuL4uEisC7vh7nb5ZXR17m0bz0dc11JWqs

-- Dumped from database version 13.23 (Debian 13.23-1.pgdg13+1)
-- Dumped by pg_dump version 13.23 (Debian 13.23-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: reservas; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA reservas;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: control_cambios; Type: TABLE; Schema: reservas; Owner: -
--

CREATE TABLE reservas.control_cambios (
    id integer NOT NULL,
    actor_tipo character varying(30) NOT NULL,
    actor_id integer,
    actor_nombre character varying(255) NOT NULL,
    accion character varying(30) NOT NULL,
    entidad character varying(80) NOT NULL,
    entidad_id integer,
    descripcion text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: control_cambios_id_seq; Type: SEQUENCE; Schema: reservas; Owner: -
--

ALTER TABLE reservas.control_cambios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reservas.control_cambios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: espacios; Type: TABLE; Schema: reservas; Owner: -
--

CREATE TABLE reservas.espacios (
    id integer NOT NULL,
    id_unidad integer NOT NULL,
    nombre character varying(100) NOT NULL,
    ubicacion character varying(255),
    capacidad integer NOT NULL,
    descripcion text,
    habilitado boolean DEFAULT true NOT NULL,
    CONSTRAINT espacios_capacidad_check CHECK ((capacidad > 0))
);


--
-- Name: espacios_id_seq; Type: SEQUENCE; Schema: reservas; Owner: -
--

ALTER TABLE reservas.espacios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reservas.espacios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laboratorios_config; Type: TABLE; Schema: reservas; Owner: -
--

CREATE TABLE reservas.laboratorios_config (
    id integer NOT NULL,
    id_unidad integer NOT NULL,
    habilitado_reservas boolean DEFAULT true NOT NULL,
    ubicacion character varying(255),
    descripcion text,
    dias_atencion jsonb DEFAULT '[0, 1, 2, 3, 4, 5]'::jsonb NOT NULL,
    hora_apertura time without time zone NOT NULL,
    hora_cierre time without time zone NOT NULL,
    horario_atencion jsonb DEFAULT '{}'::jsonb NOT NULL,
    horas_antelacion integer DEFAULT 0 NOT NULL,
    aprobacion_automatica boolean DEFAULT false NOT NULL,
    modalidad_reserva character varying(50),
    correo character varying(255),
    notificar_por_correo boolean DEFAULT false NOT NULL,
    CONSTRAINT ck_laboratorios_config_horario CHECK ((hora_apertura < hora_cierre)),
    CONSTRAINT laboratorios_config_horas_antelacion_check CHECK ((horas_antelacion >= 0))
);


--
-- Name: laboratorios_config_id_seq; Type: SEQUENCE; Schema: reservas; Owner: -
--

ALTER TABLE reservas.laboratorios_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reservas.laboratorios_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mobiliarios; Type: TABLE; Schema: reservas; Owner: -
--

CREATE TABLE reservas.mobiliarios (
    id integer NOT NULL,
    id_unidad integer NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    habilitado boolean DEFAULT true NOT NULL
);


--
-- Name: mobiliarios_id_seq; Type: SEQUENCE; Schema: reservas; Owner: -
--

ALTER TABLE reservas.mobiliarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reservas.mobiliarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: motivos_solicitud; Type: TABLE; Schema: reservas; Owner: -
--

CREATE TABLE reservas.motivos_solicitud (
    id integer NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    habilitado boolean DEFAULT true NOT NULL
);


--
-- Name: motivos_solicitud_id_seq; Type: SEQUENCE; Schema: reservas; Owner: -
--

ALTER TABLE reservas.motivos_solicitud ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reservas.motivos_solicitud_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificaciones; Type: TABLE; Schema: reservas; Owner: -
--

CREATE TABLE reservas.notificaciones (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    reserva_id integer,
    tipo character varying(20) NOT NULL,
    leida boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT notificaciones_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'APROBADA'::character varying, 'RECHAZADA'::character varying, 'CANCELADA'::character varying])::text[])))
);


--
-- Name: notificaciones_id_seq; Type: SEQUENCE; Schema: reservas; Owner: -
--

ALTER TABLE reservas.notificaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reservas.notificaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: otros; Type: TABLE; Schema: reservas; Owner: -
--

CREATE TABLE reservas.otros (
    id integer NOT NULL,
    id_unidad integer NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    habilitado boolean DEFAULT true NOT NULL
);


--
-- Name: otros_id_seq; Type: SEQUENCE; Schema: reservas; Owner: -
--

ALTER TABLE reservas.otros ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reservas.otros_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reserva_acompanantes; Type: TABLE; Schema: reservas; Owner: -
--

CREATE TABLE reservas.reserva_acompanantes (
    id integer NOT NULL,
    reserva_id integer NOT NULL,
    nombre character varying(150) NOT NULL,
    correo character varying(255)
);


--
-- Name: reserva_acompanantes_id_seq; Type: SEQUENCE; Schema: reservas; Owner: -
--

ALTER TABLE reservas.reserva_acompanantes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reservas.reserva_acompanantes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reserva_equipos; Type: TABLE; Schema: reservas; Owner: -
--

CREATE TABLE reservas.reserva_equipos (
    id integer NOT NULL,
    reserva_id integer NOT NULL,
    id_equipo integer NOT NULL
);


--
-- Name: reserva_equipos_id_seq; Type: SEQUENCE; Schema: reservas; Owner: -
--

ALTER TABLE reservas.reserva_equipos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reservas.reserva_equipos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reserva_mobiliarios; Type: TABLE; Schema: reservas; Owner: -
--

CREATE TABLE reservas.reserva_mobiliarios (
    id integer NOT NULL,
    reserva_id integer NOT NULL,
    mobiliario_id integer NOT NULL
);


--
-- Name: reserva_mobiliarios_id_seq; Type: SEQUENCE; Schema: reservas; Owner: -
--

ALTER TABLE reservas.reserva_mobiliarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reservas.reserva_mobiliarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reserva_otros; Type: TABLE; Schema: reservas; Owner: -
--

CREATE TABLE reservas.reserva_otros (
    id integer NOT NULL,
    reserva_id integer NOT NULL,
    otro_id integer NOT NULL
);


--
-- Name: reserva_otros_id_seq; Type: SEQUENCE; Schema: reservas; Owner: -
--

ALTER TABLE reservas.reserva_otros ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reservas.reserva_otros_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservas; Type: TABLE; Schema: reservas; Owner: -
--

CREATE TABLE reservas.reservas (
    id integer NOT NULL,
    id_unidad integer NOT NULL,
    espacio_id integer,
    fecha date NOT NULL,
    hora_inicio time without time zone NOT NULL,
    hora_fin time without time zone NOT NULL,
    asistentes integer NOT NULL,
    ubicacion_uso character varying(255),
    tipo_uso character varying(30) NOT NULL,
    tipo_reserva_id integer NOT NULL,
    motivo_solicitud_id integer,
    estado character varying(20) DEFAULT 'PENDIENTE'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    id_cuenta bigint NOT NULL,
    CONSTRAINT ck_reservas_horario CHECK ((hora_inicio < hora_fin)),
    CONSTRAINT ck_reservas_tipo_uso CHECK (((((tipo_uso)::text = 'ESPACIO_RESERVADO'::text) AND (espacio_id IS NOT NULL)) OR (((tipo_uso)::text = 'DENTRO_CAMPUS'::text) AND ((espacio_id IS NOT NULL) OR (NULLIF(btrim((ubicacion_uso)::text), ''::text) IS NOT NULL))) OR (((tipo_uso)::text = 'FUERA_CAMPUS'::text) AND (espacio_id IS NULL) AND (NULLIF(btrim((ubicacion_uso)::text), ''::text) IS NOT NULL)))),
    CONSTRAINT reservas_asistentes_check CHECK ((asistentes >= 0)),
    CONSTRAINT reservas_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'APROBADA'::character varying, 'RECHAZADA'::character varying, 'CANCELADA'::character varying])::text[]))),
    CONSTRAINT reservas_tipo_uso_check CHECK (((tipo_uso)::text = ANY ((ARRAY['ESPACIO_RESERVADO'::character varying, 'DENTRO_CAMPUS'::character varying, 'FUERA_CAMPUS'::character varying])::text[])))
);


--
-- Name: reservas_id_seq; Type: SEQUENCE; Schema: reservas; Owner: -
--

ALTER TABLE reservas.reservas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reservas.reservas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipos_reserva; Type: TABLE; Schema: reservas; Owner: -
--

CREATE TABLE reservas.tipos_reserva (
    id integer NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    habilitado boolean DEFAULT true NOT NULL
);


--
-- Name: tipos_reserva_id_seq; Type: SEQUENCE; Schema: reservas; Owner: -
--

ALTER TABLE reservas.tipos_reserva ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reservas.tipos_reserva_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: control_cambios control_cambios_pkey; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.control_cambios
    ADD CONSTRAINT control_cambios_pkey PRIMARY KEY (id);


--
-- Name: espacios espacios_pkey; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.espacios
    ADD CONSTRAINT espacios_pkey PRIMARY KEY (id);


--
-- Name: laboratorios_config laboratorios_config_id_unidad_key; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.laboratorios_config
    ADD CONSTRAINT laboratorios_config_id_unidad_key UNIQUE (id_unidad);


--
-- Name: laboratorios_config laboratorios_config_pkey; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.laboratorios_config
    ADD CONSTRAINT laboratorios_config_pkey PRIMARY KEY (id);


--
-- Name: mobiliarios mobiliarios_pkey; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.mobiliarios
    ADD CONSTRAINT mobiliarios_pkey PRIMARY KEY (id);


--
-- Name: motivos_solicitud motivos_solicitud_pkey; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.motivos_solicitud
    ADD CONSTRAINT motivos_solicitud_pkey PRIMARY KEY (id);


--
-- Name: notificaciones notificaciones_pkey; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.notificaciones
    ADD CONSTRAINT notificaciones_pkey PRIMARY KEY (id);


--
-- Name: otros otros_pkey; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.otros
    ADD CONSTRAINT otros_pkey PRIMARY KEY (id);


--
-- Name: reserva_acompanantes reserva_acompanantes_pkey; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reserva_acompanantes
    ADD CONSTRAINT reserva_acompanantes_pkey PRIMARY KEY (id);


--
-- Name: reserva_equipos reserva_equipos_pkey; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reserva_equipos
    ADD CONSTRAINT reserva_equipos_pkey PRIMARY KEY (id);


--
-- Name: reserva_mobiliarios reserva_mobiliarios_pkey; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reserva_mobiliarios
    ADD CONSTRAINT reserva_mobiliarios_pkey PRIMARY KEY (id);


--
-- Name: reserva_otros reserva_otros_pkey; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reserva_otros
    ADD CONSTRAINT reserva_otros_pkey PRIMARY KEY (id);


--
-- Name: reservas reservas_pkey; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reservas
    ADD CONSTRAINT reservas_pkey PRIMARY KEY (id);


--
-- Name: tipos_reserva tipos_reserva_pkey; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.tipos_reserva
    ADD CONSTRAINT tipos_reserva_pkey PRIMARY KEY (id);


--
-- Name: espacios uq_espacios_unidad_nombre; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.espacios
    ADD CONSTRAINT uq_espacios_unidad_nombre UNIQUE (id_unidad, nombre);


--
-- Name: reserva_equipos uq_reserva_equipo; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reserva_equipos
    ADD CONSTRAINT uq_reserva_equipo UNIQUE (reserva_id, id_equipo);


--
-- Name: reserva_mobiliarios uq_reserva_mobiliario; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reserva_mobiliarios
    ADD CONSTRAINT uq_reserva_mobiliario UNIQUE (reserva_id, mobiliario_id);


--
-- Name: reserva_otros uq_reserva_otro; Type: CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reserva_otros
    ADD CONSTRAINT uq_reserva_otro UNIQUE (reserva_id, otro_id);


--
-- Name: ix_notificaciones_usuario; Type: INDEX; Schema: reservas; Owner: -
--

CREATE INDEX ix_notificaciones_usuario ON reservas.notificaciones USING btree (usuario_id, leida);


--
-- Name: ix_reserva_equipos_equipo; Type: INDEX; Schema: reservas; Owner: -
--

CREATE INDEX ix_reserva_equipos_equipo ON reservas.reserva_equipos USING btree (id_equipo);


--
-- Name: ix_reserva_mobiliarios_mobiliario; Type: INDEX; Schema: reservas; Owner: -
--

CREATE INDEX ix_reserva_mobiliarios_mobiliario ON reservas.reserva_mobiliarios USING btree (mobiliario_id);


--
-- Name: ix_reserva_otros_otro; Type: INDEX; Schema: reservas; Owner: -
--

CREATE INDEX ix_reserva_otros_otro ON reservas.reserva_otros USING btree (otro_id);


--
-- Name: ix_reservas_fecha_estado; Type: INDEX; Schema: reservas; Owner: -
--

CREATE INDEX ix_reservas_fecha_estado ON reservas.reservas USING btree (fecha, estado);


--
-- Name: ix_reservas_unidad_fecha; Type: INDEX; Schema: reservas; Owner: -
--

CREATE INDEX ix_reservas_unidad_fecha ON reservas.reservas USING btree (id_unidad, fecha);


--
-- Name: espacios espacios_id_unidad_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.espacios
    ADD CONSTRAINT espacios_id_unidad_fkey FOREIGN KEY (id_unidad) REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad);


--
-- Name: reservas fk_reservas_cuenta; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reservas
    ADD CONSTRAINT fk_reservas_cuenta FOREIGN KEY (id_cuenta) REFERENCES auth.cuentas(id_cuenta);


--
-- Name: laboratorios_config laboratorios_config_id_unidad_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.laboratorios_config
    ADD CONSTRAINT laboratorios_config_id_unidad_fkey FOREIGN KEY (id_unidad) REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad);


--
-- Name: mobiliarios mobiliarios_id_unidad_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.mobiliarios
    ADD CONSTRAINT mobiliarios_id_unidad_fkey FOREIGN KEY (id_unidad) REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad);


--
-- Name: notificaciones notificaciones_reserva_id_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.notificaciones
    ADD CONSTRAINT notificaciones_reserva_id_fkey FOREIGN KEY (reserva_id) REFERENCES reservas.reservas(id) ON DELETE CASCADE;


--
-- Name: otros otros_id_unidad_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.otros
    ADD CONSTRAINT otros_id_unidad_fkey FOREIGN KEY (id_unidad) REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad);


--
-- Name: reserva_acompanantes reserva_acompanantes_reserva_id_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reserva_acompanantes
    ADD CONSTRAINT reserva_acompanantes_reserva_id_fkey FOREIGN KEY (reserva_id) REFERENCES reservas.reservas(id) ON DELETE CASCADE;


--
-- Name: reserva_equipos reserva_equipos_id_equipo_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reserva_equipos
    ADD CONSTRAINT reserva_equipos_id_equipo_fkey FOREIGN KEY (id_equipo) REFERENCES equipos.equipos(id_equipo);


--
-- Name: reserva_equipos reserva_equipos_reserva_id_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reserva_equipos
    ADD CONSTRAINT reserva_equipos_reserva_id_fkey FOREIGN KEY (reserva_id) REFERENCES reservas.reservas(id) ON DELETE CASCADE;


--
-- Name: reserva_mobiliarios reserva_mobiliarios_mobiliario_id_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reserva_mobiliarios
    ADD CONSTRAINT reserva_mobiliarios_mobiliario_id_fkey FOREIGN KEY (mobiliario_id) REFERENCES reservas.mobiliarios(id);


--
-- Name: reserva_mobiliarios reserva_mobiliarios_reserva_id_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reserva_mobiliarios
    ADD CONSTRAINT reserva_mobiliarios_reserva_id_fkey FOREIGN KEY (reserva_id) REFERENCES reservas.reservas(id) ON DELETE CASCADE;


--
-- Name: reserva_otros reserva_otros_otro_id_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reserva_otros
    ADD CONSTRAINT reserva_otros_otro_id_fkey FOREIGN KEY (otro_id) REFERENCES reservas.otros(id);


--
-- Name: reserva_otros reserva_otros_reserva_id_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reserva_otros
    ADD CONSTRAINT reserva_otros_reserva_id_fkey FOREIGN KEY (reserva_id) REFERENCES reservas.reservas(id) ON DELETE CASCADE;


--
-- Name: reservas reservas_espacio_id_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reservas
    ADD CONSTRAINT reservas_espacio_id_fkey FOREIGN KEY (espacio_id) REFERENCES reservas.espacios(id);


--
-- Name: reservas reservas_id_unidad_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reservas
    ADD CONSTRAINT reservas_id_unidad_fkey FOREIGN KEY (id_unidad) REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad);


--
-- Name: reservas reservas_motivo_solicitud_id_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reservas
    ADD CONSTRAINT reservas_motivo_solicitud_id_fkey FOREIGN KEY (motivo_solicitud_id) REFERENCES reservas.motivos_solicitud(id);


--
-- Name: reservas reservas_tipo_reserva_id_fkey; Type: FK CONSTRAINT; Schema: reservas; Owner: -
--

ALTER TABLE ONLY reservas.reservas
    ADD CONSTRAINT reservas_tipo_reserva_id_fkey FOREIGN KEY (tipo_reserva_id) REFERENCES reservas.tipos_reserva(id);


--
-- PostgreSQL database dump complete
--

\unrestrict A7ATLIsPnIEfaY9r3cfj13H6G1ykKsuL4uEisC7vh7nb5ZXR17m0bz0dc11JWqs

