-- Ajuste estructural de reservas sobre el inventario vacío verificado.
-- No ejecutar automáticamente desde el backend antiguo.
-- Ejecutar con psql -v ON_ERROR_STOP=1. No modifica otros schemas.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

-- Bloquear primero y abortar si apareció información desde la inspección.
DO $$
DECLARE t record; occupied boolean;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'reservas' ORDER BY tablename LOOP
    EXECUTE format('LOCK TABLE reservas.%I IN ACCESS EXCLUSIVE MODE', t.tablename);
    EXECUTE format('SELECT EXISTS (SELECT 1 FROM reservas.%I)', t.tablename) INTO occupied;
    IF occupied THEN RAISE EXCEPTION 'La tabla reservas.% contiene datos; ajuste cancelado', t.tablename; END IF;
  END LOOP;
END $$;

-- Sin CASCADE: una dependencia no prevista debe abortar toda la operación.
DROP TABLE reservas.reserva_equipos, reservas.reserva_mobiliarios, reservas.reserva_otros;
DROP TABLE reservas.reserva_acompanantes;
ALTER TABLE reservas.reservas
  DROP COLUMN espacio_id, DROP COLUMN fecha, DROP COLUMN hora_inicio,
  DROP COLUMN hora_fin, DROP COLUMN asistentes, DROP COLUMN ubicacion_uso,
  DROP COLUMN tipo_uso, DROP COLUMN motivo_solicitud_id, DROP COLUMN estado;
DROP TABLE reservas.motivos_solicitud;
DROP TABLE reservas.control_cambios, reservas.notificaciones;
DROP TABLE reservas.mobiliarios, reservas.otros;
-- Sus catálogos objetivo pertenecen al schema externo recursos, aún pendiente.

ALTER TABLE reservas.tipos_reserva
  ADD COLUMN codigo varchar(40) NOT NULL UNIQUE,
  ALTER COLUMN descripcion SET NOT NULL,
  ADD COLUMN created_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
CREATE TABLE reservas.estados_reserva (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar(30) UNIQUE NOT NULL,
  nombre varchar(100) NOT NULL,
  habilitado boolean NOT NULL DEFAULT true
);
CREATE TABLE reservas.laboratorio_tipos_reserva (
  id_unidad integer REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad),
  tipo_reserva_id integer REFERENCES reservas.tipos_reserva(id),
  habilitado boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_unidad, tipo_reserva_id)
);
CREATE INDEX ix_laboratorio_tipos_habilitado ON reservas.laboratorio_tipos_reserva(tipo_reserva_id, habilitado);
ALTER TABLE reservas.reservas
  ADD COLUMN estado_id integer NOT NULL REFERENCES reservas.estados_reserva(id),
  ADD COLUMN observacion text,
  ADD COLUMN requiere_apoyo boolean NOT NULL DEFAULT false,
  ADD COLUMN created_by bigint NOT NULL REFERENCES auth.cuentas(id_cuenta),
  ADD COLUMN fecha_aprobacion timestamptz,
  ADD COLUMN fecha_cancelacion timestamptz,
  ADD COLUMN motivo_cancelacion text;
CREATE INDEX ix_reservas_cuenta_created ON reservas.reservas(id_cuenta, created_at);
CREATE INDEX ix_reservas_unidad_estado ON reservas.reservas(id_unidad, estado_id);
CREATE INDEX ix_reservas_tipo_estado ON reservas.reservas(tipo_reserva_id, estado_id);

CREATE TABLE reservas.reserva_espacio (
  reserva_id integer PRIMARY KEY REFERENCES reservas.reservas(id),
  espacio_id integer NOT NULL REFERENCES reservas.espacios(id),
  fecha date NOT NULL,
  hora_inicio time NOT NULL,
  hora_fin time NOT NULL,
  asistentes integer NOT NULL DEFAULT 0 CHECK (asistentes >= 0),
  periodo tsrange GENERATED ALWAYS AS (
    CASE WHEN fecha IS NOT NULL AND hora_inicio IS NOT NULL AND hora_fin IS NOT NULL
      THEN tsrange(fecha + hora_inicio, fecha + hora_fin, '[)') ELSE NULL::tsrange END
  ) STORED,
  bloqueante boolean NOT NULL DEFAULT false,
  CHECK (hora_inicio < hora_fin)
);
CREATE TABLE reservas.reserva_acompanantes (
  reserva_id integer REFERENCES reservas.reservas(id),
  id_cuenta bigint REFERENCES auth.cuentas(id_cuenta),
  PRIMARY KEY (reserva_id, id_cuenta)
);
CREATE TABLE reservas.reserva_recurso_interno (
  reserva_id integer PRIMARY KEY REFERENCES reservas.reservas(id),
  fecha date NOT NULL, hora_inicio time NOT NULL, hora_fin time NOT NULL,
  CHECK (hora_inicio < hora_fin)
);
CREATE TABLE reservas.reserva_recurso_campus (
  reserva_id integer PRIMARY KEY REFERENCES reservas.reservas(id),
  fecha_salida date NOT NULL, fecha_devolucion_estimada date NOT NULL,
  CHECK (fecha_devolucion_estimada >= fecha_salida)
);
CREATE TABLE reservas.reserva_recurso_externo (
  reserva_id integer PRIMARY KEY REFERENCES reservas.reservas(id),
  fecha_salida date NOT NULL, fecha_devolucion_estimada date NOT NULL,
  CHECK (fecha_devolucion_estimada >= fecha_salida)
);
CREATE TABLE reservas.reserva_lista_espera (
  reserva_id integer PRIMARY KEY REFERENCES reservas.reservas(id),
  descripcion_necesidad text NOT NULL, viable boolean,
  fecha_evaluacion_viabilidad timestamptz, fecha_recepcion_material timestamptz,
  prioridad integer, horas_ejecucion numeric CHECK (horas_ejecucion >= 0)
);
CREATE TABLE reservas.reserva_lista_espera_formulario (
  reserva_id integer PRIMARY KEY REFERENCES reservas.reservas(id),
  datos_usuario jsonb NOT NULL, diligenciado_at timestamptz NOT NULL,
  datos_tecnico jsonb, revisado_por bigint REFERENCES auth.cuentas(id_cuenta), revisado_at timestamptz,
  CHECK (num_nonnulls(datos_tecnico, revisado_por, revisado_at) IN (0,3))
);
CREATE TABLE reservas.reserva_recursos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id integer NOT NULL REFERENCES reservas.reservas(id),
  recurso_id integer NOT NULL,
  rol varchar(20) NOT NULL CHECK (rol IN ('PRINCIPAL', 'ADICIONAL')),
  estado_asignacion varchar(20) NOT NULL CHECK (estado_asignacion IN ('ASIGNADO', 'NO_DISPONIBLE', 'RETIRADO')),
  incorporado_at timestamptz, periodo tstzrange,
  bloqueante boolean NOT NULL DEFAULT false
);
CREATE INDEX ix_reserva_recursos_estado ON reservas.reserva_recursos(recurso_id, estado_asignacion);
CREATE INDEX ix_reserva_recursos_reserva ON reservas.reserva_recursos(reserva_id, recurso_id);
CREATE UNIQUE INDEX uq_reserva_recursos_activo ON reservas.reserva_recursos(reserva_id, recurso_id)
  WHERE estado_asignacion <> 'RETIRADO';
CREATE UNIQUE INDEX uq_reserva_recursos_principal ON reservas.reserva_recursos(reserva_id)
  WHERE rol = 'PRINCIPAL' AND estado_asignacion = 'ASIGNADO';

CREATE TABLE reservas.reserva_contexto (
  reserva_id integer PRIMARY KEY REFERENCES reservas.reservas(id),
  proyecto_id integer REFERENCES investigacion.proyectos(id_proyecto),
  semillero_id integer REFERENCES investigacion.semilleros(id_semillero),
  pasantia_id integer, trabajo_grado_id integer, actividad_institucional_id integer,
  proyecto_codigo varchar(50), proyecto_nombre varchar(255),
  semillero_codigo varchar(50), semillero_nombre varchar(150), actividad_nombre varchar(255),
  pasantia_universidad varchar(255), pasantia_docente_nombre varchar(150), pasantia_docente_correo varchar(150),
  trabajo_grado_director_nombre varchar(150), trabajo_grado_director_correo varchar(150),
  CONSTRAINT ck_reserva_contexto_composicion CHECK (
    (actividad_institucional_id IS NULL AND num_nonnulls(proyecto_id, semillero_id, pasantia_id, trabajo_grado_id) >= 1)
    OR (actividad_institucional_id IS NOT NULL AND num_nonnulls(proyecto_id, semillero_id, pasantia_id, trabajo_grado_id) = 0)
  )
);

-- Dependencias internas del schema, definidas por el módulo Espacios.
ALTER TABLE reservas.espacios
  ADD COLUMN created_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
CREATE INDEX ix_espacios_unidad_habilitado ON reservas.espacios(id_unidad, habilitado);
CREATE INDEX ix_espacios_nombre ON reservas.espacios(nombre);
CREATE TABLE reservas.espacio_campos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  espacio_id integer NOT NULL REFERENCES reservas.espacios(id), nombre varchar(150) NOT NULL,
  tipo_campo varchar(30) NOT NULL CHECK (tipo_campo IN ('TEXTO','TEXTO_LARGO','NUMERO','BOOLEANO','SELECCION')),
  obligatorio boolean NOT NULL DEFAULT false, orden integer NOT NULL CHECK (orden >= 0),
  habilitado boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (espacio_id, nombre)
);
CREATE INDEX ix_espacio_campos_orden ON reservas.espacio_campos(espacio_id, habilitado, orden);
CREATE TABLE reservas.espacio_campo_opciones (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campo_id integer NOT NULL REFERENCES reservas.espacio_campos(id), valor varchar(255) NOT NULL,
  orden integer NOT NULL CHECK (orden >= 0), habilitado boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (campo_id, valor)
);
CREATE INDEX ix_espacio_opciones_orden ON reservas.espacio_campo_opciones(campo_id, habilitado, orden);
CREATE TABLE reservas.espacio_recursos (
  espacio_id integer REFERENCES reservas.espacios(id), recurso_id integer,
  habilitado boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (espacio_id, recurso_id)
);
CREATE INDEX ix_espacio_recursos_habilitado ON reservas.espacio_recursos(recurso_id, habilitado);
CREATE INDEX ix_espacio_recursos_espacio ON reservas.espacio_recursos(espacio_id, habilitado);
CREATE UNIQUE INDEX uq_espacio_recursos_recurso_activo ON reservas.espacio_recursos(recurso_id) WHERE habilitado;
CREATE TABLE reservas.reserva_campos_valores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id integer NOT NULL REFERENCES reservas.reservas(id),
  campo_id integer NOT NULL REFERENCES reservas.espacio_campos(id),
  campo_nombre_snapshot varchar(150) NOT NULL, campo_tipo_snapshot varchar(30) NOT NULL,
  obligatorio_snapshot boolean NOT NULL, valor_texto text,
  opcion_id integer REFERENCES reservas.espacio_campo_opciones(id), opcion_nombre_snapshot varchar(255),
  UNIQUE (reserva_id, campo_id)
);
CREATE TABLE reservas.reserva_adjuntos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id integer NOT NULL REFERENCES reservas.reservas(id),
  tipo_adjunto varchar(30) NOT NULL CHECK (tipo_adjunto IN ('PLANO','IMAGEN','DOCUMENTO')),
  nombre_original varchar(255) NOT NULL CHECK (btrim(nombre_original) <> ''),
  storage_key varchar(255) NOT NULL CONSTRAINT uq_reserva_adjuntos_storage_key UNIQUE,
  content_type varchar(100) NOT NULL,
  size_bytes integer NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 5242880),
  uploaded_by bigint NOT NULL REFERENCES auth.cuentas(id_cuenta),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_reserva_adjuntos_created ON reservas.reserva_adjuntos(reserva_id, created_at);
CREATE TABLE reservas.reserva_ejecucion_recursos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_recurso_id integer NOT NULL REFERENCES reservas.reserva_recursos(id),
  entregado_por bigint NOT NULL REFERENCES auth.cuentas(id_cuenta),
  recibido_por bigint REFERENCES auth.cuentas(id_cuenta),
  entregado_at timestamptz NOT NULL, devuelto_at timestamptz,
  observacion_entrega text, observacion_devolucion text,
  CHECK (devuelto_at >= entregado_at), CHECK ((recibido_por IS NULL) = (devuelto_at IS NULL))
);
CREATE UNIQUE INDEX uq_reserva_entrega_abierta ON reservas.reserva_ejecucion_recursos(reserva_recurso_id) WHERE devuelto_at IS NULL;
CREATE TABLE reservas.reserva_datos_salida (
  reserva_id integer PRIMARY KEY REFERENCES reservas.reservas(id), razon_solicitud text NOT NULL,
  nombre_actividad_evento varchar(255), lugar_nombre varchar(150) NOT NULL, lugar_direccion varchar(255) NOT NULL
);
CREATE TABLE reservas.ordenes_salida (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id integer UNIQUE NOT NULL REFERENCES reservas.reservas(id), fecha_generacion timestamptz NOT NULL,
  razon_solicitud text NOT NULL, nombre_actividad_evento varchar(255),
  lugar_nombre varchar(150) NOT NULL, lugar_direccion varchar(255) NOT NULL,
  dependencia_solicitante_snapshot varchar(255) NOT NULL,
  fecha_retiro_snapshot date NOT NULL, fecha_regreso_snapshot date NOT NULL,
  proyecto_codigo_snapshot varchar(60), responsable_nombre_snapshot varchar(150) NOT NULL,
  responsable_cedula_snapshot varchar(20) NOT NULL, responsable_correo_snapshot varchar(255) NOT NULL,
  responsable_telefono_snapshot varchar(20) NOT NULL, observaciones text
);
CREATE TABLE reservas.orden_salida_actividades (
  orden_salida_id integer REFERENCES reservas.ordenes_salida(id),
  actividad varchar(30) CHECK (actividad IN ('PROYECTO_INVESTIGACION','SEMILLERO_INVESTIGACION','SERVICIO_EXTENSION','PROYECTO_ACADEMICO','CALIBRACION','DOCENCIA','MANTENIMIENTO','OTRO')),
  PRIMARY KEY (orden_salida_id, actividad)
);
CREATE TABLE reservas.orden_salida_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_salida_id integer NOT NULL REFERENCES reservas.ordenes_salida(id),
  reserva_recurso_id integer NOT NULL REFERENCES reservas.reserva_recursos(id),
  placa_snapshot varchar(40), descripcion_snapshot varchar(255) NOT NULL, bodega_snapshot varchar(100),
  cc_snapshot varchar(30), fecha_compra_snapshot date,
  UNIQUE (orden_salida_id, reserva_recurso_id)
);
CREATE INDEX ix_orden_items_recurso ON reservas.orden_salida_items(reserva_recurso_id);
CREATE TABLE reservas.reserva_propuestas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id integer NOT NULL REFERENCES reservas.reservas(id),
  origen varchar(10) NOT NULL CHECK (origen IN ('TECNICO','USUARIO')),
  fecha_inicio_propuesta date NOT NULL, fecha_fin_propuesta date NOT NULL,
  hora_inicio time, hora_fin time, motivo text NOT NULL,
  estado varchar(15) NOT NULL CHECK (estado IN ('VIGENTE','ACEPTADA','RECHAZADA','SUSTITUIDA')),
  creada_por bigint NOT NULL REFERENCES auth.cuentas(id_cuenta), resuelta_por bigint REFERENCES auth.cuentas(id_cuenta),
  created_at timestamptz NOT NULL DEFAULT now(), resuelta_at timestamptz,
  CHECK (fecha_fin_propuesta >= fecha_inicio_propuesta), CHECK (hora_inicio < hora_fin)
);
CREATE UNIQUE INDEX uq_reserva_propuesta_vigente ON reservas.reserva_propuestas(reserva_id) WHERE estado = 'VIGENTE';
CREATE INDEX ix_reserva_propuestas_created ON reservas.reserva_propuestas(reserva_id, created_at);
CREATE TABLE reservas.reserva_historial_estado (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id integer NOT NULL REFERENCES reservas.reservas(id),
  estado_anterior_id integer REFERENCES reservas.estados_reserva(id),
  estado_nuevo_id integer NOT NULL REFERENCES reservas.estados_reserva(id),
  actor_cuenta_id bigint REFERENCES auth.cuentas(id_cuenta), motivo text,
  created_at timestamptz NOT NULL DEFAULT now(), CHECK (estado_nuevo_id <> estado_anterior_id)
);
CREATE INDEX ix_reserva_historial_created ON reservas.reserva_historial_estado(reserva_id, created_at);
ALTER TABLE reservas.laboratorios_config
  ADD COLUMN mostrar_estado_reserva boolean NOT NULL DEFAULT false,
  ADD COLUMN mostrar_reservista boolean NOT NULL DEFAULT false,
  ADD COLUMN recordatorio_horas_antes integer NOT NULL DEFAULT 24 CHECK (recordatorio_horas_antes > 0);

CREATE TABLE reservas.laboratorios_config_historico (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_unidad integer NOT NULL REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad),
  dias_atencion jsonb NOT NULL, hora_apertura time NOT NULL, hora_cierre time NOT NULL,
  horario_atencion jsonb NOT NULL, vigente_desde timestamptz NOT NULL, vigente_hasta timestamptz,
  CHECK (hora_apertura < hora_cierre), CHECK (vigente_hasta > vigente_desde),
  EXCLUDE USING gist (id_unidad WITH =, tstzrange(vigente_desde, vigente_hasta, '[)') WITH &&)
);
CREATE UNIQUE INDEX uq_laboratorio_horario_vigente ON reservas.laboratorios_config_historico(id_unidad)
  WHERE vigente_hasta IS NULL;

-- Las FK externas se completan en el paso 003; no se aceptan identificadores
-- huérfanos mientras las tablas propietarias no existen.
ALTER TABLE reservas.reserva_recursos ADD CONSTRAINT pendiente_fk_recursos CHECK (recurso_id IS NULL);
ALTER TABLE reservas.espacio_recursos ADD CONSTRAINT pendiente_fk_recursos CHECK (recurso_id IS NULL);
ALTER TABLE reservas.reserva_contexto
  ADD CONSTRAINT pendiente_fk_pasantias CHECK (pasantia_id IS NULL),
  ADD CONSTRAINT pendiente_fk_trabajos_grado CHECK (trabajo_grado_id IS NULL),
  ADD CONSTRAINT pendiente_fk_actividades CHECK (actividad_institucional_id IS NULL);
COMMIT;
