-- Schema recursos: catálogo raíz y sus tres especializaciones (DB-01).
--
-- recursos.recursos es el catálogo unificado objetivo de resources/data-model.md.
-- Cada especialización usa el mismo id como PK/FK, sin identidad propia ni
-- duplicar id_unidad/habilitado, que pertenecen al catálogo raíz. Cuál
-- especialización corresponde a un recurso lo decide su fila en
-- recursos.recursos.tipo; la aplicación garantiza que exista exactamente una
-- fila hija compatible al crearlo (no es un CHECK entre tablas).
--
-- Desbloquea DB-05: reserva_recursos.recurso_id y espacio_recursos.recurso_id
-- referencian recursos.recursos(id), hoy impedidas por pendiente_fk_recursos.
--
-- reservas.laboratorios_config y su histórico NO son de esta migración: ya
-- están aplicadas desde 002 (grupo "Configuración por unidad").
--
-- Sin CASCADE: una dependencia no prevista debe abortar, no borrarse.
-- Última sentencia: la fila del ledger (convención de 011_gobierno.sql).
--
-- Ejecutar con: psql -v ON_ERROR_STOP=1

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

CREATE SCHEMA recursos;

CREATE TABLE recursos.categorias_equipos (
    id_categoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       varchar(50) NOT NULL
);

CREATE TABLE recursos.recursos (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad  integer NOT NULL REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad),
    tipo       varchar(20) NOT NULL CHECK (tipo IN ('EQUIPO', 'MOBILIARIO', 'OTRO')),
    habilitado boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_recursos_unidad_tipo ON recursos.recursos(id_unidad, tipo);

CREATE TABLE recursos.equipos (
    id                          integer PRIMARY KEY REFERENCES recursos.recursos(id),
    nombre_equipo               varchar(100) NOT NULL,
    placa                       varchar(40) UNIQUE,
    serial                      varchar(50) UNIQUE,
    marca                       varchar(50),
    modelo                      varchar(50),
    image_path                  varchar(100),
    manual_operacion            varchar(100),
    requiere_calibracion        boolean,
    guia_rapida                 varchar(100),
    instalador                  varchar(100),
    estado                      boolean,
    requiere_apoyo              boolean NOT NULL DEFAULT false,
    acreditado                  boolean NOT NULL DEFAULT false,
    id_categoria                integer REFERENCES recursos.categorias_equipos(id_categoria),
    proxima_fecha_calibracion   date,
    proxima_fecha_mantenimiento date,
    frecuencia_calibracion      integer,
    frecuencia_mantenimiento    integer,
    bodega                      varchar(100),
    centro_costo                varchar(30),
    fecha_compra                date
);
CREATE INDEX ix_recursos_equipos_categoria ON recursos.equipos(id_categoria);

CREATE TABLE recursos.mobiliarios (
    id          integer PRIMARY KEY REFERENCES recursos.recursos(id),
    id_unidad   integer NOT NULL REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad),
    nombre      varchar(100) NOT NULL,
    descripcion text,
    habilitado  boolean NOT NULL DEFAULT true
);

CREATE TABLE recursos.otros_recursos (
    id          integer PRIMARY KEY REFERENCES recursos.recursos(id),
    id_unidad   integer NOT NULL REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad),
    nombre      varchar(100) NOT NULL,
    descripcion text,
    habilitado  boolean NOT NULL DEFAULT true
);

INSERT INTO public.schema_migrations (nombre) VALUES ('004_recursos');

COMMIT;
