-- Completa el schema investigacion: las once tablas que faltan de las trece
-- de researchs/data-model.md (DB-02). proyectos y semilleros ya existen.
--
-- Las cinco entidades y las seis tablas de vinculacion siguen el mismo
-- patron: identity BY DEFAULT como proyectos/semilleros ("igual que el resto
-- de entidades del schema"), estado boolean NOT NULL DEFAULT true, y NO
-- ACTION en toda FK. Desactivar conserva la fila; reactivar una vinculacion
-- existente en vez de duplicarla es responsabilidad del servicio, no del
-- esquema (RN-INV-11).
--
-- Desbloquea DB-05: reserva_contexto.pasantia_id, trabajo_grado_id y
-- actividad_institucional_id referencian estas tablas.
--
-- Sin CASCADE: una dependencia no prevista debe abortar, no borrarse.
-- Última sentencia: la fila del ledger (convención de 011_gobierno.sql).
--
-- Ejecutar con: psql -v ON_ERROR_STOP=1

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

-- --------------------------------------------------------------------------
-- Entidades
-- --------------------------------------------------------------------------

CREATE TABLE investigacion.modalidades_vinculacion (
    id_modalidad integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       varchar(100) NOT NULL UNIQUE,
    descripcion  text,
    estado       boolean NOT NULL DEFAULT true
);

CREATE TABLE investigacion.perfiles (
    id_perfil   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      varchar(100) NOT NULL UNIQUE,
    descripcion text,
    estado      boolean NOT NULL DEFAULT true
);

CREATE TABLE investigacion.actividades_institucionales (
    id_actividad integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       varchar(255) NOT NULL,
    dependencia  varchar(255) NOT NULL,
    estado       boolean NOT NULL DEFAULT true
);

CREATE TABLE investigacion.pasantias (
    id_pasantia        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    universidad        varchar(255) NOT NULL,
    docente_itm_nombre varchar(150) NOT NULL,
    docente_itm_correo varchar(150) NOT NULL,
    estado             boolean NOT NULL DEFAULT true
);

CREATE TABLE investigacion.trabajos_grado (
    id_trabajo_grado integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    director_nombre  varchar(150) NOT NULL,
    director_correo  varchar(150) NOT NULL,
    estado           boolean NOT NULL DEFAULT true
);

-- --------------------------------------------------------------------------
-- Vinculaciones con usuarios.usuarios(id_usuario)
-- --------------------------------------------------------------------------

CREATE TABLE investigacion.usuario_pasantias (
    id_usuario_pasantia integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario          bigint NOT NULL REFERENCES usuarios.usuarios(id_usuario),
    id_pasantia         integer NOT NULL REFERENCES investigacion.pasantias(id_pasantia),
    estado              boolean NOT NULL DEFAULT true,
    UNIQUE (id_usuario, id_pasantia)
);

CREATE TABLE investigacion.usuario_trabajos_grado (
    id_usuario_trabajo_grado integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario               bigint NOT NULL REFERENCES usuarios.usuarios(id_usuario),
    id_trabajo_grado         integer NOT NULL REFERENCES investigacion.trabajos_grado(id_trabajo_grado),
    estado                   boolean NOT NULL DEFAULT true,
    UNIQUE (id_usuario, id_trabajo_grado)
);

CREATE TABLE investigacion.usuario_modalidades_vinculacion (
    id_vinculacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario     bigint NOT NULL REFERENCES usuarios.usuarios(id_usuario),
    id_modalidad   integer NOT NULL REFERENCES investigacion.modalidades_vinculacion(id_modalidad),
    fecha_inicio   date,
    fecha_fin      date,
    descripcion    text,
    estado         boolean NOT NULL DEFAULT true,
    CHECK (fecha_fin IS NULL OR fecha_inicio IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE TABLE investigacion.usuario_perfiles (
    id_usuario   bigint NOT NULL REFERENCES usuarios.usuarios(id_usuario),
    id_perfil    integer NOT NULL REFERENCES investigacion.perfiles(id_perfil),
    fecha_inicio date,
    fecha_fin    date,
    estado       boolean NOT NULL DEFAULT true,
    PRIMARY KEY (id_usuario, id_perfil),
    CHECK (fecha_fin IS NULL OR fecha_inicio IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE TABLE investigacion.usuario_proyectos (
    id_usuario   bigint NOT NULL REFERENCES usuarios.usuarios(id_usuario),
    id_proyecto  integer NOT NULL REFERENCES investigacion.proyectos(id_proyecto),
    fecha_inicio date,
    fecha_fin    date,
    estado       boolean NOT NULL DEFAULT true,
    PRIMARY KEY (id_usuario, id_proyecto),
    CHECK (fecha_fin IS NULL OR fecha_inicio IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE TABLE investigacion.usuario_semilleros (
    id_usuario    bigint NOT NULL REFERENCES usuarios.usuarios(id_usuario),
    id_semillero  integer NOT NULL REFERENCES investigacion.semilleros(id_semillero),
    fecha_inicio  date,
    fecha_fin     date,
    estado        boolean NOT NULL DEFAULT true,
    PRIMARY KEY (id_usuario, id_semillero),
    CHECK (fecha_fin IS NULL OR fecha_inicio IS NULL OR fecha_fin >= fecha_inicio)
);

INSERT INTO public.schema_migrations (nombre) VALUES ('005_investigacion');

COMMIT;
