-- Schema administration: auditoria, importaciones e importacion_resultados
-- (DB-03). unidadOrganizacional.unidad_organizacional y cargos.cargo ya
-- existen; no son de esta migración.
--
-- administration.auditoria sustituye a reservas.control_cambios: actor_id
-- sin FK se reemplaza por actor_cuenta_id con FK real a auth.cuentas
-- (RN-AUD-01). No hay datos en produccion que migrar.
--
-- Sin CASCADE: una dependencia no prevista debe abortar, no borrarse.
-- Última sentencia: la fila del ledger (convención de 011_gobierno.sql).
--
-- Ejecutar con: psql -v ON_ERROR_STOP=1

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

CREATE SCHEMA administration;

CREATE TABLE administration.auditoria (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_cuenta_id  bigint NOT NULL REFERENCES auth.cuentas(id_cuenta),
    entidad          varchar(80) NOT NULL,
    entidad_id       varchar(80) NOT NULL,
    accion           varchar(40) NOT NULL,
    datos_anteriores jsonb,
    datos_nuevos     jsonb,
    motivo           text,
    created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_auditoria_entidad ON administration.auditoria(entidad, entidad_id, created_at);
CREATE INDEX ix_auditoria_actor ON administration.auditoria(actor_cuenta_id, created_at);

CREATE TABLE administration.importaciones (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_cuenta_id         bigint NOT NULL REFERENCES auth.cuentas(id_cuenta),
    catalogo                varchar(40) NOT NULL CHECK (catalogo IN ('PROYECTOS', 'SEMILLEROS', 'EQUIPOS')),
    archivo_referencia      varchar(255) NOT NULL,
    registros_creados       integer NOT NULL DEFAULT 0 CHECK (registros_creados >= 0),
    registros_actualizados  integer NOT NULL DEFAULT 0 CHECK (registros_actualizados >= 0),
    registros_desactivados  integer NOT NULL DEFAULT 0 CHECK (registros_desactivados >= 0),
    created_at              timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_importaciones_catalogo ON administration.importaciones(catalogo, created_at);

CREATE TABLE administration.importacion_resultados (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    importacion_id integer NOT NULL REFERENCES administration.importaciones(id),
    numero_fila    integer NOT NULL CHECK (numero_fila > 0),
    codigo         varchar(255),
    resultado      varchar(20) NOT NULL CHECK (resultado IN ('CREADO', 'ACTUALIZADO', 'DESACTIVADO', 'ERROR')),
    detalle        text,
    UNIQUE (importacion_id, numero_fila)
);

INSERT INTO public.schema_migrations (nombre) VALUES ('006_administration');

COMMIT;
