-- Schema notificaciones: catalogo de eventos, ocurrencias, bandeja in-app,
-- envios de correo y preferencias (DB-04), conforme a
-- notifications/data-model.md. Sustituye a la unica tabla reservas.notificaciones
-- del inventario (usuario_id sin FK, CHECK heredado): el destinatario pasa a
-- ser id_cuenta bigint con FK real a auth.cuentas.
--
-- Sin CASCADE: una dependencia no prevista debe abortar, no borrarse.
-- Última sentencia: la fila del ledger (convención de 011_gobierno.sql).
--
-- Ejecutar con: psql -v ON_ERROR_STOP=1

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

CREATE SCHEMA notificaciones;

CREATE TABLE notificaciones.tipos_evento (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      varchar(40) NOT NULL UNIQUE,
    nombre      varchar(100) NOT NULL,
    descripcion text,
    habilitado  boolean NOT NULL DEFAULT true
);

CREATE TABLE notificaciones.eventos (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_evento_id   integer NOT NULL REFERENCES notificaciones.tipos_evento(id),
    reserva_id       integer REFERENCES reservas.reservas(id),
    ocurrencia_clave varchar(160) NOT NULL UNIQUE,
    created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE notificaciones.notificaciones (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id  bigint NOT NULL REFERENCES notificaciones.eventos(id),
    id_cuenta  bigint NOT NULL REFERENCES auth.cuentas(id_cuenta),
    titulo     varchar(255) NOT NULL,
    cuerpo     text NOT NULL,
    leida_at   timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (evento_id, id_cuenta)
);
CREATE INDEX ix_notificaciones_bandeja ON notificaciones.notificaciones(id_cuenta, leida_at, created_at);
CREATE INDEX ix_notificaciones_evento ON notificaciones.notificaciones(evento_id);

CREATE TABLE notificaciones.envios_correo (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id           bigint NOT NULL REFERENCES notificaciones.eventos(id),
    notificacion_id     bigint UNIQUE REFERENCES notificaciones.notificaciones(id),
    destinatario_correo varchar(255) NOT NULL,
    titulo              varchar(255) NOT NULL,
    cuerpo              text NOT NULL,
    estado              varchar(15) NOT NULL CHECK (estado IN ('PENDIENTE', 'ENVIADO', 'FALLIDO', 'ANULADO')),
    intentos            integer NOT NULL DEFAULT 0 CHECK (intentos >= 0),
    proximo_intento_at  timestamptz,
    ultimo_error        text,
    enviado_at          timestamptz,
    anulado_at          timestamptz,
    motivo_anulacion    text,
    created_at          timestamptz NOT NULL DEFAULT now(),
    UNIQUE (evento_id, destinatario_correo),
    -- anulado_at y motivo_anulacion solo si (y siempre que) el estado sea ANULADO.
    CHECK (
        (estado = 'ANULADO' AND anulado_at IS NOT NULL AND motivo_anulacion IS NOT NULL)
        OR (estado <> 'ANULADO' AND anulado_at IS NULL AND motivo_anulacion IS NULL)
    ),
    -- un envio anulado no puede tener enviado_at ni reintento pendiente.
    CHECK (estado <> 'ANULADO' OR (enviado_at IS NULL AND proximo_intento_at IS NULL))
);
CREATE INDEX ix_envios_correo_reintento ON notificaciones.envios_correo(estado, proximo_intento_at);

CREATE TABLE notificaciones.envio_correo_adjuntos (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    envio_correo_id bigint NOT NULL REFERENCES notificaciones.envios_correo(id),
    orden           smallint NOT NULL CHECK (orden > 0),
    nombre_original varchar(255) NOT NULL,
    storage_key     varchar(500) NOT NULL,
    content_type    varchar(100) NOT NULL,
    size_bytes      bigint NOT NULL CHECK (size_bytes >= 0),
    contenido_hash  varchar(128) NOT NULL,
    UNIQUE (envio_correo_id, orden)
);

CREATE TABLE notificaciones.preferencias (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta         bigint NOT NULL REFERENCES auth.cuentas(id_cuenta),
    tipo_evento_id    integer REFERENCES notificaciones.tipos_evento(id),
    correo_habilitado boolean NOT NULL DEFAULT true
);
-- Una preferencia general por cuenta y una por tipo de evento; dos parciales
-- en vez de NULLS NOT DISTINCT, que PostgreSQL 13 no soporta.
CREATE UNIQUE INDEX uq_preferencias_por_tipo
    ON notificaciones.preferencias(id_cuenta, tipo_evento_id)
    WHERE tipo_evento_id IS NOT NULL;
CREATE UNIQUE INDEX uq_preferencias_general
    ON notificaciones.preferencias(id_cuenta)
    WHERE tipo_evento_id IS NULL;

INSERT INTO public.schema_migrations (nombre) VALUES ('007_notificaciones');

COMMIT;
