-- Tablas objetivo de auth: sesiones, invitaciones, tokens de recuperación,
-- permisos y sus asignaciones (DB-14).
--
-- auth.cuentas ya existe y no se toca. Los catorce códigos del catálogo los
-- carga DB-09; aquí solo la estructura. Definiciones de auth/data-model.md.
--
-- Sin CASCADE: una dependencia no prevista debe abortar, no borrarse.
-- Última sentencia: la fila del ledger (convención de 011_gobierno.sql).
--
-- Ejecutar con: psql -v ON_ERROR_STOP=1

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

CREATE TABLE auth.sesiones (
    id_sesion           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    id_cuenta           bigint NOT NULL REFERENCES auth.cuentas(id_cuenta) ON DELETE CASCADE,
    refresh_token_hash  varchar(255) NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    expires_at          timestamptz NOT NULL CHECK (expires_at > created_at),
    revoked_at          timestamptz,
    ultima_actividad_at timestamptz NOT NULL DEFAULT now(),
    reautenticado_at    timestamptz
);

CREATE TABLE auth.invitaciones (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo      varchar(255) NOT NULL,
    tipo_cuenta varchar(20) NOT NULL CHECK (tipo_cuenta IN ('USUARIO', 'PERSONAL')),
    id_usuario  bigint REFERENCES usuarios.usuarios(id_usuario),
    id_persona  integer REFERENCES personal.personal(id_persona),
    token_hash  varchar(255) NOT NULL UNIQUE,
    expira_at   timestamptz NOT NULL,
    usada_at    timestamptz,
    revocada_at timestamptz,
    creada_por  bigint NOT NULL REFERENCES auth.cuentas(id_cuenta),
    created_at  timestamptz NOT NULL DEFAULT now(),
    CHECK (expira_at > created_at)
);
-- Solo una invitación utilizable por correo. Sin now() en el predicado:
-- no es inmutable; la expiración la evalúa la aplicación (SEC-INV-02).
CREATE UNIQUE INDEX uq_invitaciones_correo_utilizable
    ON auth.invitaciones(correo)
    WHERE usada_at IS NULL AND revocada_at IS NULL;

CREATE TABLE auth.tokens_recuperacion (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta   bigint NOT NULL REFERENCES auth.cuentas(id_cuenta),
    token_hash  varchar(255) NOT NULL UNIQUE,
    expira_at   timestamptz NOT NULL,
    usado_at    timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CHECK (expira_at > created_at)
);
CREATE INDEX ix_tokens_recuperacion_cuenta
    ON auth.tokens_recuperacion(id_cuenta, created_at);

CREATE TABLE auth.permisos (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      varchar(60) NOT NULL UNIQUE,
    nombre      varchar(100) NOT NULL,
    descripcion text,
    habilitado  boolean NOT NULL DEFAULT true
);

CREATE TABLE auth.cuenta_permisos (
    id_cuenta_permiso bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta        bigint NOT NULL REFERENCES auth.cuentas(id_cuenta),
    permiso_id       integer NOT NULL REFERENCES auth.permisos(id),
    id_unidad        integer REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad),
    otorgado_por     bigint NOT NULL REFERENCES auth.cuentas(id_cuenta),
    created_at       timestamptz NOT NULL DEFAULT now()
);
-- id_unidad admite NULL (alcance global). Dos parciales en lugar de
-- NULLS NOT DISTINCT, que PostgreSQL 13 no soporta.
CREATE UNIQUE INDEX uq_cuenta_permiso_unidad
    ON auth.cuenta_permisos(id_cuenta, permiso_id, id_unidad)
    WHERE id_unidad IS NOT NULL;
CREATE UNIQUE INDEX uq_cuenta_permiso_global
    ON auth.cuenta_permisos(id_cuenta, permiso_id)
    WHERE id_unidad IS NULL;

INSERT INTO public.schema_migrations (nombre) VALUES ('010_auth_objetivo');

COMMIT;
