-- Schemas compartidos: auth, usuarios, personal, cargos, unidadOrganizacional
-- e investigacion, reconstruidos desde la especificacion.
--
-- POR QUE EXISTE ESTE ARCHIVO
-- Estos schemas venian de una base compartida con otros sistemas del ITM y
-- ningun script de este repositorio los creaba. Al perderse el volumen de
-- PostgreSQL desaparecieron, y con ellos la unica linea base que habia.
-- Se reconstruyen desde los data-model, que los definen por completo.
--
-- QUE ESTADO REPRODUCE
-- El anterior a las migraciones planificadas, no el objetivo. Las
-- incorporaciones que el modelo marca como pendientes NO se crean aqui,
-- para que sus tareas sigan siendo reales y verificables:
--
--   DB-06  personal.personal.estado -> NOT NULL DEFAULT true
--   DB-07  unidad_organizacional.estado
--   DB-14  las cinco tablas objetivo de auth
--   DB-15  usuarios.usuarios: documento, telefono, institucion, dependencia
--
-- Crear aqui el estado objetivo dejaria esas cuatro tareas sin nada que hacer
-- y sin forma de comprobar que la migracion funciona.
--
-- Ejecutar con: psql -v ON_ERROR_STOP=1

BEGIN;

-- btree_gist lo necesita 002 para la exclusion de vigencias de
-- laboratorios_config_historico. En la base original ya estaba instalada.
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE SCHEMA IF NOT EXISTS "unidadOrganizacional";
CREATE SCHEMA IF NOT EXISTS cargos;
CREATE SCHEMA IF NOT EXISTS usuarios;
CREATE SCHEMA IF NOT EXISTS personal;
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS investigacion;

-- --------------------------------------------------------------------------
-- Estructura institucional
-- --------------------------------------------------------------------------

CREATE TABLE "unidadOrganizacional".unidad_organizacional (
    id_unidad        integer GENERATED BY DEFAULT AS IDENTITY,
    nombre           varchar(100) NOT NULL,
    tipo             varchar(50)  NOT NULL,
    id_unidad_padre  integer,
    CONSTRAINT pk_unidad_organizacional PRIMARY KEY (id_unidad),
    CONSTRAINT uq_unidad_organizacional_nombre UNIQUE (nombre),
    CONSTRAINT fk_unidad_organizacional_padre FOREIGN KEY (id_unidad_padre)
        REFERENCES "unidadOrganizacional".unidad_organizacional (id_unidad)
);
-- estado: lo agrega DB-07.

CREATE TABLE cargos.cargo (
    id_cargo      integer GENERATED ALWAYS AS IDENTITY,
    nombre_cargo  varchar(50) NOT NULL,
    id_unidad     integer NOT NULL,
    CONSTRAINT pk_cargo PRIMARY KEY (id_cargo),
    CONSTRAINT fk_cargo_unidad FOREIGN KEY (id_unidad)
        REFERENCES "unidadOrganizacional".unidad_organizacional (id_unidad)
);

-- --------------------------------------------------------------------------
-- Identidades funcionales
-- --------------------------------------------------------------------------

CREATE TABLE usuarios.usuarios (
    id_usuario             bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre                 varchar(150) NOT NULL,
    correo                 varchar(255) NOT NULL,
    estado                 boolean NOT NULL DEFAULT true,
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),
    perfil_actualizado_at  timestamptz,
    CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuarios_correo UNIQUE (correo)
);
-- documento, telefono, institucion, dependencia y el CHECK de nombre: DB-15.

CREATE TABLE personal.personal (
    id_persona  integer GENERATED ALWAYS AS IDENTITY,
    nombre      varchar(50)  NOT NULL,
    id_cargo    integer      NOT NULL,
    documento   varchar(20)  NOT NULL,
    correo      varchar(255) NOT NULL,
    telefono    varchar(20)  NOT NULL,
    estado      boolean,
    CONSTRAINT pk_personal PRIMARY KEY (id_persona),
    CONSTRAINT uq_personal_documento UNIQUE (documento),
    CONSTRAINT uq_personal_correo UNIQUE (correo),
    CONSTRAINT uq_personal_telefono UNIQUE (telefono),
    CONSTRAINT fk_personal_cargo FOREIGN KEY (id_cargo)
        REFERENCES cargos.cargo (id_cargo)
);
-- estado queda nullable a proposito: NOT NULL DEFAULT true es DB-06.

-- --------------------------------------------------------------------------
-- Cuentas
-- --------------------------------------------------------------------------

CREATE TABLE auth.cuentas (
    id_cuenta      bigint GENERATED BY DEFAULT AS IDENTITY,
    correo         varchar(255) NOT NULL,
    password_hash  varchar(255) NOT NULL,
    tipo_cuenta    varchar(20)  NOT NULL,
    id_usuario     bigint,
    id_persona     integer,
    estado         boolean NOT NULL DEFAULT true,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_auth_cuentas PRIMARY KEY (id_cuenta),
    CONSTRAINT uq_auth_cuentas_correo UNIQUE (correo),
    CONSTRAINT uq_auth_cuentas_usuario UNIQUE (id_usuario),
    CONSTRAINT uq_auth_cuentas_persona UNIQUE (id_persona),
    CONSTRAINT fk_auth_cuentas_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuarios.usuarios (id_usuario),
    CONSTRAINT fk_auth_cuentas_persona FOREIGN KEY (id_persona)
        REFERENCES personal.personal (id_persona),
    CONSTRAINT ck_auth_cuentas_tipo
        CHECK (tipo_cuenta IN ('USUARIO', 'PERSONAL')),
    -- Exactamente una identidad: es USUARIO o PERSONAL, nunca ambas ni ninguna.
    CONSTRAINT ck_auth_cuentas_identidad CHECK (
        (tipo_cuenta = 'USUARIO'  AND id_usuario IS NOT NULL AND id_persona IS NULL)
     OR (tipo_cuenta = 'PERSONAL' AND id_persona IS NOT NULL AND id_usuario IS NULL)
    )
);
-- sesiones, invitaciones, tokens_recuperacion, permisos y cuenta_permisos: DB-14.

-- --------------------------------------------------------------------------
-- Investigacion
-- --------------------------------------------------------------------------

CREATE TABLE investigacion.proyectos (
    id_proyecto  integer GENERATED BY DEFAULT AS IDENTITY,
    codigo       varchar(50)  NOT NULL,
    nombre       varchar(255) NOT NULL,
    estado       boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_proyectos PRIMARY KEY (id_proyecto),
    CONSTRAINT uq_proyectos_codigo UNIQUE (codigo)
);

CREATE TABLE investigacion.semilleros (
    id_semillero  integer GENERATED BY DEFAULT AS IDENTITY,
    codigo        varchar(50)  NOT NULL,
    nombre        varchar(150) NOT NULL,
    estado        boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_semilleros PRIMARY KEY (id_semillero),
    CONSTRAINT uq_semilleros_codigo UNIQUE (codigo)
);
-- pasantias, trabajos_grado, actividades_institucionales, perfiles,
-- modalidades_vinculacion y las seis tablas de vinculacion: DB-02.

-- --------------------------------------------------------------------------
-- Heredado: solo para que 001 pueda ejecutarse
-- --------------------------------------------------------------------------
-- Ninguna especificacion define equipos.equipos: es del esquema anterior, y
-- 001 lo referencia desde reservas.reserva_equipos. 002 retira esa tabla, asi
-- que el schema queda huerfano y 003 lo elimina. El modelo objetivo lo
-- sustituye por recursos.equipos (DB-01), y el inventario real llega por
-- importacion masiva (API-12), no por este schema.

CREATE SCHEMA IF NOT EXISTS equipos;

CREATE TABLE equipos.equipos (
    id_equipo integer GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT pk_equipos PRIMARY KEY (id_equipo)
);

COMMIT;
