-- Migración estructural del modelo SDD.
-- Ejecutar conectado a la única base PostgreSQL compartida.
-- No contiene reglas de aplicación, ORM ni lógica de autorización.

BEGIN;

CREATE SCHEMA IF NOT EXISTS reservas;
CREATE SCHEMA IF NOT EXISTS reservas_legacy;

-- El public heredado se conserva como archivo de datos. La operación es
-- reversible y evita borrar reservas históricas durante la transición.
DO $$
DECLARE
    tabla text;
BEGIN
    FOR tabla IN
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_type = 'BASE TABLE'
    LOOP
        EXECUTE format('ALTER TABLE public.%I SET SCHEMA reservas_legacy', tabla);
    END LOOP;
END $$;

-- Compatibilidad de la tabla maestra existente con la identidad autenticada.
ALTER TABLE IF EXISTS personal.personal
    ADD COLUMN IF NOT EXISTS supabase_id UUID;
CREATE UNIQUE INDEX IF NOT EXISTS uq_personal_supabase_id
    ON personal.personal (supabase_id)
    WHERE supabase_id IS NOT NULL;
ALTER TABLE IF EXISTS personal.personal
    ALTER COLUMN correo TYPE VARCHAR(150);

CREATE TABLE IF NOT EXISTS reservas.usuarios (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(80) NOT NULL UNIQUE,
    email               VARCHAR(255) NOT NULL UNIQUE,
    hashed_password     VARCHAR(255) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reservas.laboratorios_config (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad           INTEGER NOT NULL UNIQUE
        REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad),
    habilitado_reservas BOOLEAN NOT NULL DEFAULT TRUE,
    ubicacion           VARCHAR(255),
    descripcion         TEXT,
    dias_atencion       JSONB NOT NULL DEFAULT '[0,1,2,3,4,5]'::jsonb,
    hora_apertura       TIME NOT NULL,
    hora_cierre         TIME NOT NULL,
    horario_atencion    JSONB NOT NULL DEFAULT '{}'::jsonb,
    horas_antelacion    INTEGER NOT NULL DEFAULT 0 CHECK (horas_antelacion >= 0),
    aprobacion_automatica BOOLEAN NOT NULL DEFAULT FALSE,
    modalidad_reserva   VARCHAR(50),
    correo              VARCHAR(255),
    notificar_por_correo BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT ck_laboratorios_config_horario CHECK (hora_apertura < hora_cierre)
);

CREATE TABLE IF NOT EXISTS reservas.espacios (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad           INTEGER NOT NULL
        REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad),
    nombre              VARCHAR(100) NOT NULL,
    ubicacion           VARCHAR(255),
    capacidad           INTEGER NOT NULL CHECK (capacidad > 0),
    descripcion         TEXT,
    habilitado          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_espacios_unidad_nombre UNIQUE (id_unidad, nombre)
);

CREATE TABLE IF NOT EXISTS reservas.mobiliarios (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad           INTEGER NOT NULL
        REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad),
    nombre              VARCHAR(100) NOT NULL,
    descripcion         TEXT,
    habilitado          BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS reservas.otros (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad           INTEGER NOT NULL
        REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad),
    nombre              VARCHAR(100) NOT NULL,
    descripcion         TEXT,
    habilitado          BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS reservas.tipos_reserva (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(100) NOT NULL,
    descripcion         TEXT,
    habilitado          BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS reservas.motivos_solicitud (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(100) NOT NULL,
    descripcion         TEXT,
    habilitado          BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS reservas.reservas (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          INTEGER NOT NULL REFERENCES reservas.usuarios(id),
    id_unidad           INTEGER NOT NULL
        REFERENCES "unidadOrganizacional".unidad_organizacional(id_unidad),
    espacio_id          INTEGER REFERENCES reservas.espacios(id),
    fecha               DATE NOT NULL,
    hora_inicio         TIME NOT NULL,
    hora_fin            TIME NOT NULL,
    asistentes          INTEGER NOT NULL CHECK (asistentes >= 0),
    ubicacion_uso       VARCHAR(255),
    tipo_uso            VARCHAR(30) NOT NULL CHECK
        (tipo_uso IN ('ESPACIO_RESERVADO', 'DENTRO_CAMPUS', 'FUERA_CAMPUS')),
    tipo_reserva_id     INTEGER NOT NULL REFERENCES reservas.tipos_reserva(id),
    motivo_solicitud_id INTEGER REFERENCES reservas.motivos_solicitud(id),
    estado              VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE' CHECK
        (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA', 'CANCELADA')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_reservas_horario CHECK (hora_inicio < hora_fin),
    CONSTRAINT ck_reservas_tipo_uso CHECK (
        (tipo_uso = 'ESPACIO_RESERVADO' AND espacio_id IS NOT NULL)
        OR (tipo_uso = 'DENTRO_CAMPUS' AND
            (espacio_id IS NOT NULL OR NULLIF(trim(ubicacion_uso), '') IS NOT NULL))
        OR (tipo_uso = 'FUERA_CAMPUS' AND espacio_id IS NULL AND
            NULLIF(trim(ubicacion_uso), '') IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS reservas.reserva_equipos (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id          INTEGER NOT NULL REFERENCES reservas.reservas(id) ON DELETE CASCADE,
    id_equipo           INTEGER NOT NULL REFERENCES equipos.equipos(id_equipo),
    CONSTRAINT uq_reserva_equipo UNIQUE (reserva_id, id_equipo)
);

CREATE TABLE IF NOT EXISTS reservas.reserva_mobiliarios (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id          INTEGER NOT NULL REFERENCES reservas.reservas(id) ON DELETE CASCADE,
    mobiliario_id       INTEGER NOT NULL REFERENCES reservas.mobiliarios(id),
    CONSTRAINT uq_reserva_mobiliario UNIQUE (reserva_id, mobiliario_id)
);

CREATE TABLE IF NOT EXISTS reservas.reserva_otros (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id          INTEGER NOT NULL REFERENCES reservas.reservas(id) ON DELETE CASCADE,
    otro_id             INTEGER NOT NULL REFERENCES reservas.otros(id),
    CONSTRAINT uq_reserva_otro UNIQUE (reserva_id, otro_id)
);

CREATE TABLE IF NOT EXISTS reservas.reserva_acompanantes (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id          INTEGER NOT NULL REFERENCES reservas.reservas(id) ON DELETE CASCADE,
    nombre              VARCHAR(150) NOT NULL,
    correo              VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS reservas.notificaciones (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          INTEGER NOT NULL REFERENCES reservas.usuarios(id) ON DELETE CASCADE,
    reserva_id          INTEGER REFERENCES reservas.reservas(id) ON DELETE CASCADE,
    tipo                VARCHAR(20) NOT NULL CHECK
        (tipo IN ('PENDIENTE', 'APROBADA', 'RECHAZADA', 'CANCELADA')),
    leida               BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reservas.control_cambios (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_tipo          VARCHAR(30) NOT NULL,
    actor_id            INTEGER,
    actor_nombre        VARCHAR(255) NOT NULL,
    accion              VARCHAR(30) NOT NULL,
    entidad             VARCHAR(80) NOT NULL,
    entidad_id          INTEGER,
    descripcion         TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_reservas_fecha_estado
    ON reservas.reservas (fecha, estado);
CREATE INDEX IF NOT EXISTS ix_reservas_unidad_fecha
    ON reservas.reservas (id_unidad, fecha);
CREATE INDEX IF NOT EXISTS ix_reserva_equipos_equipo
    ON reservas.reserva_equipos (id_equipo);
CREATE INDEX IF NOT EXISTS ix_reserva_mobiliarios_mobiliario
    ON reservas.reserva_mobiliarios (mobiliario_id);
CREATE INDEX IF NOT EXISTS ix_reserva_otros_otro
    ON reservas.reserva_otros (otro_id);
CREATE INDEX IF NOT EXISTS ix_notificaciones_usuario
    ON reservas.notificaciones (usuario_id, leida);

COMMIT;
